apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-test-dev
  namespace: argo-test-dev
spec:
  releaseName: argo-test-dev
  targetNamespace: argo-test-dev
  chart:
    spec:
      chart: standard-webapp
      version: "v1.0.x"
      sourceRef:
        kind: HelmRepository
        name: aperam
        namespace: flux-system
  interval: 30m
  install:
    remediation:
      retries: 3
  values:
    applicationName: argo-test
    replicaCount: 2
    image:
      repository: "acrjdlsharedpoc01.azurecr.io/argo-test" # {"$imagepolicy": "argo-test-dev:argo-test-dev:name"}
      tag: "1.1.0" # {"$imagepolicy": "argo-test-dev:argo-test-dev:tag"}
      pullPolicy: Always
    serviceAccount:
      create: true
      name: ""
    service:
      type: ClusterIP
      port: 8000
      containerPort: 8000
    environment:
      enabled: false
    secrets:
      enabled: false
    ingress:
      enabled: true
      className: nginx-pub
      hosts:
        - host: argo-test.dev.delaet.dev
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: argo-test-dev-delaet-dev-tls
          hosts:
            - argo-test.dev.delaet.dev
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 75
      targetMemoryUtilizationPercentage: 75
    tolerations:
      - key: CriticalAddonsOnly
        operator: Equal
        value: "true"
        effect: NoSchedule
