{{- range .Values.cronJobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule | quote }}
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          {{- with .podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: {{ .containerName }}
            {{- with .securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: {{ .image }}
            imagePullPolicy: {{ .imagePullPolicy }}
            {{- with .command }}
            command:
              {{- range . }}
              - {{ . | quote }}
              {{- end }}
            {{- end }}
            {{- with .args }}
            args:
              {{- range . }}
              - {{ . | quote }}
              {{- end }}
            {{- end }}
          restartPolicy: {{ .restartPolicy }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
