on:
  pull_request_target:
    types: [opened]

jobs:
  annotate-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Annotate pull request
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## :white_check_mark: Pull request checklist
            - [ ] I have read the [contributing](https://github.com/certeu/m365-assessment-infrastructure/blob/main/CONTRIBUTING.md) guidelines
            - [ ] I have reviewed my own changes

            ## Checklist for IaC changes
            - [ ] I have added documentation for my changes
            - [ ] I have updated the README where needed

            ## Checklist for constituent onboardings
            - [ ] I have read the [service onboarding](https://github.com/certeu/m365-assessment-infrastructure/blob/main/docs/operations/service-onboarding.md) documentation
            - [ ] I have included the associated ITSM ticket number in the PR title
            - [ ] I have included a link to the ITSM ticket in the PR description
            - [ ] I have included the relevant information related to the constituent's assessment configuration in the PR description

            `
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            })
