name: Scan with Trivy

on:
  pull_request_target:
    branches: main
    paths-ignore:
      - .github/*

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy scan
        uses: dexmach-enterprise-nfr/action-composite-trivy-scan@v1
        with:
          container-registry-endpoint: ${{ vars.REGISTRY_ENDPOINT }}
          container-project-name: ${{ vars.DOCKER_PROJECT_NAME }}
          container-image-name: ${{ vars.DOCKER_IMAGE_NAME }}
          trivy-config-path: trivy.yaml